DROP TABLE IF EXISTS Users

CREATE TABLE Users(
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(249) NOT NULL UNIQUE,
    Email VARCHAR(249) NOT NULL UNIQUE,
    Password BIGINT NOT NULL,
    Created_at TIMESTAMP,
    Update_at TIMESTAMP ,
)


